CREATE TABLE inventory (id INTEGER PRIMARY KEY AUTOINCREMENT, name unique, category integer, quantity integer, price real, salePrice real, description text);
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, firstname text, lastname text, username unique, password text, email text, admin boolean);
CREATE TABLE categories (id INTEGER PRIMARY KEY AUTOINCREMENT, category text);
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Hat and Wand Combo', 1, 7, 1.8, 1.7, 'Can''t really have one without the other... Am I right?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Anything is Possible Bottle', 2, 3, 1.9, 1.9, 'A bottle, where anything is possible.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Confetti Wand', 6, 7, 1.12, 1.12, 'A wand that explodes with confetti.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Cumberband Servante', 3, 7, 101.45, 1.3, 'You fancy, huh?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Build Your Own Illusions', 1, 7, 4.8, 3.2, 'A DvD, Self-explainitory. We will come to your home and hit you outside the head with a baseball bat if you need a better dexcription than that. ');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Cash Flow', 6, 7, 4.8, 3.2, 'Make it rain, but with magic. So, not actually.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Change Bag', 8, 7, 4.8, 3.2, 'Socailism.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('3d Multiplaying Rabits', 10, 7, 1.56, 1.56, 'You can buy this or two real bunnies and watch them actually multiply.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Threesome', 5, 7, 3.33, 2.22, 'I think its a book about magic... I think?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Birthday Card Surprise', 6, 7, 22.56, 0.56, 'SURPRISE!!!');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Black Hat', 2, 7, 1.56, 1.56, 'Not Red Hat, Black Hat.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('testitem1', 1, 7, 1.56, 1.56, 'This is the first item');
INSERT INTO categories(category) VALUES ('Bottles');
INSERT INTO categories(category) VALUES ('Hats');
INSERT INTO categories(category) VALUES ('Wands');
INSERT INTO categories(category) VALUES ('DVDS');
INSERT INTO categories(category) VALUES ('Books');
INSERT INTO categories(category) VALUES ('Cards');
INSERT INTO categories(category) VALUES ('Ropes');
INSERT INTO categories(category) VALUES ('Pranks and Gags');
INSERT INTO categories(category) VALUES ('Ventriloquist Dolls');
INSERT INTO categories(category) VALUES ('Other');
INSERT INTO users(firstname, lastname, username, password, email, admin) VALUES('John', 'Doe', 'johndoe', 'mypassword', 'johndoe@example.com', 1);
