CREATE TABLE inventory (id INTEGER PRIMARY KEY AUTOINCREMENT, name unique, category integer, quantity integer, price real, salePrice real, description text);
CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, firstname text, lastname text, username unique, password text, email text, admin boolean);
CREATE TABLE categories (id INTEGER PRIMARY KEY AUTOINCREMENT, category text);
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Hat and Wand Combo', 2, 7, 22.45, 22.45, 'Can''t really have one without the other... Am I right?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Anything is Possible Bottle', 1, 3, 11.9, 10.9, 'A bottle, where anything is possible.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Confetti Wand', 3, 7, 10.12, 10.12, 'A wand that explodes with confetti.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Confetti Wand Refils', 3, 7, 11.45, 11.45, 'Self-explanitory.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Cumberband Servante', 7, 7, 101.45, 100.3, 'You fancy, huh?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Build Your Own Illusions', 4, 7, 40.8, 30.2, 'A DvD, should be self-explainitory. We will come to your home and hit you outside the head with a baseball bat if you need a better dexcription than that. ');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Cash Flow', 4, 7, 33.8, 33.8, 'Make it rain, but with magic. So, not actually.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Change Bag', 7, 7, 4.8, 3.2, 'Socailism.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Three-D Multiplaying Rabits', 7, 7, 1.56, 1.56, 'You can buy this or two real bunnies and watch them actually multiply.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Threesome', 5, 7, 3.33, 2.22, 'I think its a book about magic... I think?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Birthday Card Surprise', 6, 7, 22.56, 0.56, 'SURPRISE!!!');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Black Hat', 2, 7, 1.56, 1.56, 'Not Red Hat, Black Hat.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Always Full, Always Empty', 7, 7, 10.56, 10.56, 'The Glass is at 50%, end of story.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Amazing Magic Finger Chopper', 7, 7, 1.56, 1.56, 'Does not work with toes!');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Cloaking Device', 7, 7, 15.56, 15.56, 'A device that cloaks things, who knew?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Dynamo Deck', 6, 7, 13.34, 13.34, 'Because an ordinary card deck isn''t good enough.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Haunted Key', 7, 1, 17.56, 17.56, 'Comes with the haunted lock that it opens. Beware.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Two Piece Brass-Tipped Magic Wand', 3, 7, 22.33, 22.33, 'Aren''t all wands magicall?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Way Forcing Deck', 6, 7, 17.56, 17.56, 'For the guy who trys hard and gets no where.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Art and Ardor at the Card Table', 5, 7, 7.56, 7.56, 'An indepth review of cards, can''t get any more exciting.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('64 Winning Betchas', 5, 7, 27.53, 19.56, '99 Problems and a Betcha isn''t one of them.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('101 Easy-to-Do Magic Tricks', 5, 7, 7.53, 4.56, 'Do not attempt with out your parents permission!');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Magic for the Young Magician', 5, 10, 33.12, 19.95, 'You''re almost there, kid.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Basic Card Technique', 5, 22, 27.53, 27.52, 'Fairly Basic.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Between Two Minds', 5, 4, 15.00, 15.00, 'They say two heads are better than one. Who''s they anyways? And why would I bother to slow myself down by working along with someone else?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Codes, Ciphers and Secret Writing', 5, 9001, 27.50, 27.50, 'Be warned, after reading this book, the author will always be able to crack any ciphering done by you.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Entertaining Mathematical Puzzles', 5, 7, 5.53, 5.53, 'NERRRRRRDDDDDDDDDD!!!');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Lethal Magic', 4, 5, 35.00, 35.00, 'I LoL''d at Lethal and Magic being in the same title.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Packet Card Tricks', 4, 5, 35.00, 35.00, 'Another generic how-to-card trick dvd that could be youtube''d.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('The Royal Road to Card Magic', 4, 5, 25.00, 25.00, 'eh, maybe?');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Showoff', 4, 5, 25.00, 15.00, 'Your friends will LOVE you.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Ultimate Slow Motion Bill Transposition', 4, 5, 25.00, 25.00, 'You will love it or your money back! Or maybe not.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Street Magic', 4, 5, 20.00, 20.00, 'For those of us who don''t live on the streets.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Total Control', 4, 5, 30.00, 30.00, 'For those of us who were having dominance issues with our own playing cards.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Houdini''s School of Magic Vol. 1', 4, 5, 15.00, 15.00, 'Prepared to get schooled!');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('Coin in the Balloon', 4, 5, 20.00, 20.00, 'The key here is to put the coin inside the balloon before you blow it up. There, I saved you like 20 bucks.');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('A Wand', 3, 5, 10.00, 9.00, 'Need a wizard hat...');
INSERT INTO inventory(name, category, quantity, price, salePrice, description) VALUES('The Force', 2, 5, 1000.00, 900.00, 'The force is strong with this one.');
INSERT INTO categories(category) VALUES ('Bottles');
INSERT INTO categories(category) VALUES ('Hats');
INSERT INTO categories(category) VALUES ('Wands');
INSERT INTO categories(category) VALUES ('DVDS');
INSERT INTO categories(category) VALUES ('Books');
INSERT INTO categories(category) VALUES ('Cards');
INSERT INTO categories(category) VALUES ('Other');
INSERT INTO users(firstname, lastname, username, password, email, admin) VALUES('John', 'Doe', 'johndoe', 'mypassword', 'johndoe@example.com', 1);
